name: odmax

channels:
  - conda-forge

dependencies:
  - opencv
  - pip
  - python=3.8
  - matplotlib
  - cartopy
  - jupyter
  - pip:
    - PyExifTool
    - git+https://github.com/localdevices/py360convert.git
