name: odmax

channels:
  - conda-forge

dependencies:
  - pip==21.2.4
  - python=3.8
  - matplotlib==3.5.0
  - cartopy==0.18.0
  - jupyter==1.0.0
  - pip:
    - git+https://github.com/localdevices/py360convert.git
    - git+https://github.com/localdevices/ODMax.git
